project_id = "oafulfbetlfnrwzsfuzs"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.extract-salesforce-data]
verify_jwt = false

[functions.generate-lead-analysis]
verify_jwt = false

[functions.generate-playbook]
verify_jwt = false

[functions.research-company]
verify_jwt = false

[functions.admin-cases]
verify_jwt = false

[functions.admin-solutions]
verify_jwt = false
